name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: nn_test
      id: nn_test
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 80
        setup-command: pip install -r requirements.txt
    - name: nn_pylint
      id: nn_pylint
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: nn_pylint
        setup-command: pip install -r requirements.txt
        command: pylint nn.py || true
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        NN_TEST_RESULTS: "${{steps.nn_test.outputs.result}}"
        NN_PYLINT_RESULTS: "${{steps.nn_pylint.outputs.result}}"
      with:
        runners: nn_test,nn_pylint
